/**
 * Catppuccin Mocha palette and semantic roles. The palette mirrors the
 * ExtPorter ratatui client (`ext_analyzer/src/theme.rs`) so the two UIs read
 * as the same family: dark base, muted borders, mauve/lavender accents.
 */
export const mocha = {
  base: "#1e1e2e",
  mantle: "#181825",
  crust: "#11111b",
  surface0: "#313244",
  surface1: "#45475a",
  surface2: "#585b70",
  text: "#cdd6f4",
  subtext1: "#bac2de",
  subtext0: "#a6adc8",
  overlay2: "#9399b2",
  overlay1: "#7f849c",
  overlay0: "#6c7086",
  rosewater: "#f5e0dc",
  flamingo: "#f2cdcd",
  pink: "#f5c2e7",
  mauve: "#cba6f7",
  red: "#f38ba8",
  maroon: "#eba0ac",
  peach: "#fab387",
  yellow: "#f9e2af",
  green: "#a6e3a1",
  teal: "#94e2d5",
  sky: "#89dceb",
  sapphire: "#74c7ec",
  blue: "#89b4fa",
  lavender: "#b4befe",
} as const;

/** Semantic roles shared across the client. */
export const c = {
  brand: mocha.green,
  border: mocha.surface2,
  menuBorder: mocha.lavender,
  panelBorder: mocha.surface2,
  panelTitle: mocha.mauve,
  selected: mocha.mauve,
  text: mocha.text,
  subtext: mocha.subtext1,
  muted: mocha.overlay0,
  dim: mocha.overlay1,
  label: mocha.mauve,
  connected: mocha.green,
  connecting: mocha.yellow,
  disconnected: mocha.red,
  selectedFg: mocha.text,
  selectedBg: mocha.surface1,
  scoreHigh: mocha.green,
  scoreMedium: mocha.yellow,
  scoreLow: mocha.red,
  tested: mocha.blue,
  migrated: mocha.green,
  info: mocha.sky,
  warning: mocha.peach,
  danger: mocha.red,
  success: mocha.green,
  accent: mocha.blue,
  highlight: mocha.yellow,
  searchActive: mocha.mauve,
  searchInactive: mocha.surface2,
  searchLabel: mocha.subtext1,
  cursor: mocha.text,
} as const;
